name = "JunTools"
uuid = "82c6a4a6-4a0a-4415-915b-34a320dfc6da"
authors = ["Jun Allard <jun.allard@uci.edu>"]
version = "0.2.2"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

